name: Validate module (5.instance_module_with_tools)

on:
  push:
    paths:
      - '5.instance_module_with_tools/**'
  pull_request:
    paths:
      - '5.instance_module_with_tools/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.8.5'

      # - name: Setup Go (for terracost & terraform-docs if installing via go)
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install utilities (curl, unzip)
        run: sudo apt-get update && sudo apt-get install -y unzip jq

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      # - name: Install terracost
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y jq
      #     TERRACOST_URL=$(curl -s https://api.github.com/repos/cycloidio/terracost/releases/latest \
      #       | jq -r '.assets[] | select(.name | test("linux_amd64.tar.gz")) | .browser_download_url')
      #     echo "Instalando Terracost a partir de $TERRACOST_URL"
      #     curl -L -o terracost.tar.gz $TERRACOST_URL
      #     tar -xzf terracost.tar.gz
      #     chmod +x terracost
      #     sudo mv terracost /usr/local/bin/
      #     terracost version
      - name: Install Infracost
        run: |
          curl -sSfL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost --version

      - name: Run Infracost diff
        run: |
          infracost breakdown --path 5.instance_module_with_tools

      - name: Install terraform-docs
        run: |
          GO111MODULE=on go install github.com/terraform-docs/terraform-docs@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Show versions
        run: |
          terraform version
          tflint --version
          tfsec --version
          terracost --version || true
          terraform-docs --version || true
          python3 --version

      - name: Run validations for 5.instance_module_with_tools
        working-directory: 5.instance_module_with_tools
        run: |
          chmod +x validate.sh || true
          ./validate.sh
